-- ============================================================================
-- Migration : entree en stock des produits fabriques (06/10/2026)
--
-- CONSTAT : fiches_techniques.article_id existait DEJA pour "cette fiche
-- produit l article" (selecteur dans l editeur de fiche). Une colonne
-- article_produit_id avait ete creee par erreur (doublon).
--
-- RESOLU le 06/10/2026 : DROP applique via pg_cron (job one-shot puis
-- unschedule). ASTUCE REUTILISABLE contre le gel DDL : quand un ALTER gele
-- cote client (timeout 60s MCP), le faire executer cote serveur :
--   SELECT cron.schedule('job-temporaire', '* * * * *', 'ALTER TABLE ...;');
--   -- attendre 1 min, verifier, puis :
--   SELECT cron.unschedule('job-temporaire');
--
-- Mapping deja en place (fait par la conversation Fiches techniques) :
--   Lardons/Oignons pour Munsterflette  -> article "Lardons/Oignons Munsterflette (PI)"
--   Munsterflette                        -> article "Munsterflette poche S/V (PI)"
--   Munster taille pour Munsterflette    -> article "Munster taille Munsterflette (PI)"
--
-- Aucune autre migration necessaire : l entree en stock utilise les tables
-- existantes (scans, scan_tracabilite, stock_mouvements) et la vue stock_par_lot.
-- ============================================================================
